{{- range $index, $nodeName := .Values.trino.worker.nodes }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: trino-worker-{{ $index }}
  namespace: {{ $.Values.namespace }}
spec:
  replicas: {{ $.Values.trino.worker.replicasPerNode }}
  selector:
    matchLabels:
      app: trino-worker
      node-index: "{{$index}}"
  serviceName: trino-worker-headless
  template:
    metadata:
      labels:
        app: trino-worker
        node-index: "{{$index}}"
    spec:
      nodeName: {{ $nodeName }}
      containers:
        - name: trino
          image: {{ $.Values.trino.pod.image }}
          command: ["/bin/sh", "-c", "cd /lib/trino/bin && ./run-trino"]
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 9189
              protocol: TCP
            - containerPort: 9090
              protocol: TCP
          securityContext:
            capabilities:
              drop:
                - MKNOD
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: "4"
              memory: "64Gi"
            limits:
              cpu: "4"
              memory: "64Gi"
          volumeMounts:
            - name: pgr24jamesvol1claim
              mountPath: /mnt/primary
            - name: {{ $.Values.pvc.iceberg.name }}
              mountPath: /mnt/iceberg
            - name: trino-iceberg-config-{{ $.Values.instanceName }}
              mountPath: /etc/trino/catalog/iceberg.properties
              subPath: iceberg.properties
            - name: trino-worker-config-{{ $.Values.instanceName }}
              mountPath: /etc/trino/config.properties
              subPath: config.properties
            - name: trino-jvm-config
              mountPath: /etc/trino/jvm.config
              subPath: jvm.config
            - name: trino-jmx-config
              mountPath: /etc/jmx-exporter-config.yml
              subPath: jmx-exporter-config.yml
      volumes:
        - name: pgr24jamesvol1claim
          persistentVolumeClaim:
            claimName: pgr24jamesvol1claim
        - name: {{ $.Values.pvc.iceberg.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.pvc.iceberg.name }}
        - name: trino-iceberg-config-{{ $.Values.instanceName }}
          configMap:
            name: trino-iceberg-config-{{ $.Values.instanceName }}
        - name: trino-worker-config-{{ $.Values.instanceName }}
          configMap:
            name: trino-worker-config-{{ $.Values.instanceName }}
        - name: trino-jvm-config
          configMap:
            name: trino-jvm-config
        - name: trino-jmx-config
          configMap:
            name: trino-jmx-config
        - name: kube-api-access-kkwjn
          projected:
            sources:
              - serviceAccountToken:
                  expirationSeconds: 360700
                  path: token
              - configMap:
                  name: kube-root-ca.crt
                  items:
                    - key: ca.crt
                      path: ca.crt
              - downwardAPI:
                  items:
                    - path: namespace
                      fieldRef:
                        apiVersion: v1
                        fieldPath: metadata.namespace
              - configMap:
                  name: openshift-service-ca.crt
                  items:
                    - key: service-ca.crt
                      path: service-ca.crt
            defaultMode: 420
{{- end }}